name: magic_box
description: "一款使用 Flutter 构建的强大且多功能的桌面搜索工具。Magic Box 是一个浮动搜索工具，允许用户使用各种插件快速搜索和检索信息，提供从单一界面访问文件、应用程序和网络内容的高效方式。"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  window_manager: ^0.3.0
  file_picker: ^10.3.6
  path_provider: ^2.1.5
  archive: ^4.0.7
  path: ^1.9.0
  shared_preferences: ^2.5.3
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true